[OZ][N-11] Code Cohesion and Readability
Fantom-foundation/opera-sfc pull request #120
Opened 2024-12-13 16:50 UTC by Mike-CZ

This PR imrpoves readibility. 

The `epochEndTime` getter was made public in https://github.com/Fantom-foundation/opera-sfc/pull/119/files

2024-12-16 11:05 UTC, thaarok requested changes
Using names originatedTxsFee and accumulatedOriginatedTxsFee was correct in here.

2025-01-31 13:28 UTC, Mike-CZ commented
> Using names originatedTxsFee and accumulatedOriginatedTxsFee was correct in here.

Reverted to keep original naming.

2025-01-31 13:51 UTC, thaarok submitted a review, later dismissed

2025-01-31 14:19 UTC, thaarok approved these changes

2025-01-31 14:24 UTC, merged